# Generated by Django 3.1 on 2021-11-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinsentiment',
            name='FearIndex',
            field=models.FloatField(),
        ),
    ]
