# Generated by Django 3.1 on 2021-11-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211107_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binancecoinsentiment',
            name='FearIndex',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cardanosentiment',
            name='FearIndex',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dogecoinsentiment',
            name='FearIndex',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ethereumsentiment',
            name='FearIndex',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='litecoinsentiment',
            name='FearIndex',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='polkadotsentiment',
            name='FearIndex',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shibainusentiment',
            name='FearIndex',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solanasentiment',
            name='FearIndex',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='terrasentiment',
            name='FearIndex',
            field=models.FloatField(),
        ),
    ]
